/**
 * service.ts — install/uninstall 360router as an OS auto-start service
 *
 * Windows : Task Scheduler (ONLOGON + 30s delay, current user)
 * Linux   : systemd user service (~/.config/systemd/user/)
 * macOS   : launchd user agent (~/Library/LaunchAgents/)
 */

import chalk from 'chalk';
import { execSync, spawnSync } from 'child_process';
import { writeFileSync, unlinkSync, existsSync, mkdirSync } from 'fs';
import { homedir } from 'os';
import { join } from 'path';

const TASK_NAME   = '360Router';
const DISPLAY     = '360Router Proxy';
const DESCRIPTION = '360router AI proxy — routes AI app requests to local or cloud models';
const DELAY_SEC   = 30;

// ─── Platform helpers ──────────────────────────────────────────────────────────

function getRouterBin(): string {
  // npm global bin is on PATH; resolve the full path for task scheduler
  try {
    const r = spawnSync('where', ['360router'], { encoding: 'utf8' });
    if (r.stdout) return r.stdout.split('\n')[0].trim();
  } catch { /* fallback */ }
  // Common Windows npm global path
  const appdata = process.env.APPDATA ?? join(homedir(), 'AppData', 'Roaming');
  return join(appdata, 'npm', '360router.cmd');
}

function delaySec(s: number): string {
  const mm = String(Math.floor(s / 60)).padStart(4, '0');
  const ss = String(s % 60).padStart(2, '0');
  return `${mm}:${ss}`;
}

// ─── Windows (Startup folder — no admin required) ────────────────────────────

function getStartupDir(): string {
  return join(
    process.env.APPDATA ?? join(homedir(), 'AppData', 'Roaming'),
    'Microsoft', 'Windows', 'Start Menu', 'Programs', 'Startup'
  );
}

const VBS_FILE = '360router-serve.vbs';

function installWindows(): void {
  const bin     = getRouterBin();
  const vbsPath = join(getStartupDir(), VBS_FILE);

  // VBScript: sleep DELAY_SEC seconds then launch 360router serve hidden (no window)
  const vbs = `' 360Router auto-start — generated by 360router service install
WScript.Sleep ${DELAY_SEC * 1000}
Set oShell = CreateObject("WScript.Shell")
oShell.Run """${bin}"" serve", 0, False
`;

  try {
    writeFileSync(vbsPath, vbs);
    console.log(chalk.green('  ✓ Auto-start installed (Startup folder)'));
    console.log(chalk.dim(`    File:   ${vbsPath}`));
    console.log(chalk.dim(`    Starts: ${DELAY_SEC}s after you log in, runs hidden`));
    console.log(chalk.dim('    No admin required — runs as your user'));
  } catch (e: any) {
    console.log(chalk.red('  ✗ Could not write startup file:'));
    console.log(chalk.dim('    ' + e.message));
  }
}

function uninstallWindows(): void {
  const vbsPath = join(getStartupDir(), VBS_FILE);
  if (existsSync(vbsPath)) {
    try {
      unlinkSync(vbsPath);
      console.log(chalk.green('  ✓ Auto-start removed from Startup folder'));
    } catch (e: any) {
      console.log(chalk.red('  ✗ Could not remove: ' + e.message));
    }
  } else {
    console.log(chalk.yellow('  Auto-start was not installed (nothing to remove)'));
  }
}

function statusWindows(): void {
  const vbsPath = join(getStartupDir(), VBS_FILE);
  if (existsSync(vbsPath)) {
    console.log(chalk.green('  ✓ Auto-start is installed'));
    console.log(chalk.dim(`    ${vbsPath}`));
    console.log(chalk.dim(`    Starts ${DELAY_SEC}s after login`));
  } else {
    console.log(chalk.yellow('  Auto-start is NOT installed'));
    console.log(chalk.dim('    Run: 360router service install'));
  }
}

// ─── Linux (systemd user) ──────────────────────────────────────────────────────

function installLinux(): void {
  const dir  = join(homedir(), '.config', 'systemd', 'user');
  const file = join(dir, '360router.service');
  const bin  = execSync('which 360router', { encoding: 'utf8' }).trim();

  mkdirSync(dir, { recursive: true });

  const unit = `[Unit]
Description=${DESCRIPTION}
After=network.target

[Service]
Type=simple
ExecStartPre=/bin/sleep ${DELAY_SEC}
ExecStart=${bin} serve
Restart=on-failure
RestartSec=10

[Install]
WantedBy=default.target
`;

  writeFileSync(file, unit);
  execSync('systemctl --user daemon-reload');
  execSync('systemctl --user enable 360router.service');
  execSync('systemctl --user start 360router.service');

  console.log(chalk.green('  ✓ systemd user service installed and started'));
  console.log(chalk.dim(`    Unit: ${file}`));
  console.log(chalk.dim(`    Starts ${DELAY_SEC}s after login`));
  console.log(chalk.dim('    Check: systemctl --user status 360router'));
}

function uninstallLinux(): void {
  const file = join(homedir(), '.config', 'systemd', 'user', '360router.service');
  try { execSync('systemctl --user stop 360router.service'); } catch { /* not running */ }
  try { execSync('systemctl --user disable 360router.service'); } catch { /* not enabled */ }
  if (existsSync(file)) { unlinkSync(file); }
  try { execSync('systemctl --user daemon-reload'); } catch { /* ignore */ }
  console.log(chalk.green('  ✓ systemd service removed'));
}

function statusLinux(): void {
  try {
    const out = execSync('systemctl --user status 360router.service', { encoding: 'utf8' });
    const active = out.includes('active (running)');
    console.log(active
      ? chalk.green('  ✓ 360router service is running')
      : chalk.yellow('  ⚠ 360router service is installed but not running'));
    console.log(chalk.dim('    systemctl --user status 360router for details'));
  } catch {
    console.log(chalk.yellow('  360router service is NOT installed'));
    console.log(chalk.dim('    Run: 360router service install'));
  }
}

// ─── macOS (launchd) ──────────────────────────────────────────────────────────

function installMac(): void {
  const dir   = join(homedir(), 'Library', 'LaunchAgents');
  const plist = join(dir, 'ai.360ops.router.plist');
  const bin   = execSync('which 360router', { encoding: 'utf8' }).trim();

  mkdirSync(dir, { recursive: true });

  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>           <string>ai.360ops.router</string>
  <key>ProgramArguments</key>
  <array>
    <string>${bin}</string>
    <string>serve</string>
  </array>
  <key>RunAtLoad</key>       <true/>
  <key>KeepAlive</key>       <true/>
  <key>StartInterval</key>   <integer>${DELAY_SEC}</integer>
  <key>StandardOutPath</key> <string>${homedir()}/.360router/serve.log</string>
  <key>StandardErrorPath</key><string>${homedir()}/.360router/serve.log</string>
</dict>
</plist>`;

  mkdirSync(join(homedir(), '.360router'), { recursive: true });
  writeFileSync(plist, xml);
  execSync(`launchctl load "${plist}"`);

  console.log(chalk.green('  ✓ launchd agent installed'));
  console.log(chalk.dim(`    Plist: ${plist}`));
  console.log(chalk.dim(`    Log:   ${homedir()}/.360router/serve.log`));
}

function uninstallMac(): void {
  const plist = join(homedir(), 'Library', 'LaunchAgents', 'ai.360ops.router.plist');
  try { execSync(`launchctl unload "${plist}"`); } catch { /* not loaded */ }
  if (existsSync(plist)) { unlinkSync(plist); }
  console.log(chalk.green('  ✓ launchd agent removed'));
}

function statusMac(): void {
  try {
    const out = execSync('launchctl list ai.360ops.router', { encoding: 'utf8' });
    console.log(chalk.green('  ✓ launchd agent is installed'));
    console.log(chalk.dim('    ' + out.trim()));
  } catch {
    console.log(chalk.yellow('  launchd agent is NOT installed'));
    console.log(chalk.dim('    Run: 360router service install'));
  }
}

// ─── Public entry point ────────────────────────────────────────────────────────

export async function runService(args: string[]): Promise<void> {
  const sub = args[0] ?? 'status';
  const p   = process.platform;

  console.log(chalk.bold.cyan('\n  360Router — Auto-start Service\n'));

  switch (sub) {
    case 'install':
      if (p === 'win32') installWindows();
      else if (p === 'linux') installLinux();
      else if (p === 'darwin') installMac();
      else console.log(chalk.yellow(`  Unsupported platform: ${p}`));
      break;

    case 'uninstall':
    case 'remove':
      if (p === 'win32') uninstallWindows();
      else if (p === 'linux') uninstallLinux();
      else if (p === 'darwin') uninstallMac();
      else console.log(chalk.yellow(`  Unsupported platform: ${p}`));
      break;

    case 'status':
    default:
      if (p === 'win32') statusWindows();
      else if (p === 'linux') statusLinux();
      else if (p === 'darwin') statusMac();
      else console.log(chalk.yellow(`  Unsupported platform: ${p}`));
      break;
  }

  console.log('');
}
