/**
 * Seed data for PMI/MI combo scorer
 *
 * 572 manual entries across domains: finance, IT, legal, operations, clients, people
 * Free tier: platform + industry combos only (no phi/pii sensitive entries)
 * Pro tier: includes phi and pii sensitivity combos
 *
 * Format: tokens, domain, pmi, tier
 */

export interface DisambiguationCombo {
  tokens: string[];
  domain: string;
  pmi: number;
  tier?: 'pro'; // Only for phi_*/pii_* combos
}

/**
 * Seed disambiguation combos - domain routing entries
 * These are manually curated high-signal combinations
 */
export const SEED_COMBOS: DisambiguationCombo[] = [
  // ========== FINANCE DOMAIN ==========
  { tokens: ['quarterly', 'taxes'], domain: 'finance', pmi: 3.40 },
  { tokens: ['tax', 'return'], domain: 'finance', pmi: 3.20 },
  { tokens: ['irs', 'penalty'], domain: 'finance', pmi: 3.80 },
  { tokens: ['payroll', 'deduction'], domain: 'finance', pmi: 3.10 },
  { tokens: ['accounts', 'payable'], domain: 'finance', pmi: 4.20 },
  { tokens: ['accounts', 'receivable'], domain: 'finance', pmi: 4.20 },
  { tokens: ['balance', 'sheet'], domain: 'finance', pmi: 3.90 },
  { tokens: ['profit', 'loss'], domain: 'finance', pmi: 3.50 },
  { tokens: ['cash', 'flow'], domain: 'finance', pmi: 3.30 },
  { tokens: ['revenue', 'recognition'], domain: 'finance', pmi: 3.60 },
  { tokens: ['accrual', 'basis'], domain: 'finance', pmi: 4.10 },
  { tokens: ['depreciation', 'schedule'], domain: 'finance', pmi: 3.70 },
  { tokens: ['audit', 'report'], domain: 'finance', pmi: 2.90 },
  { tokens: ['general', 'ledger'], domain: 'finance', pmi: 4.00 },
  { tokens: ['chart', 'accounts'], domain: 'finance', pmi: 3.85 },
  { tokens: ['budget', 'forecast'], domain: 'finance', pmi: 2.80 },
  { tokens: ['expense', 'report'], domain: 'finance', pmi: 2.70 },
  { tokens: ['invoice', 'payment'], domain: 'finance', pmi: 2.95 },
  { tokens: ['bank', 'reconciliation'], domain: 'finance', pmi: 3.50 },
  { tokens: ['credit', 'memo'], domain: 'finance', pmi: 3.20 },
  { tokens: ['debit', 'memo'], domain: 'finance', pmi: 3.20 },
  { tokens: ['journal', 'entry'], domain: 'finance', pmi: 3.40 },
  { tokens: ['cost', 'center'], domain: 'finance', pmi: 2.60 },
  { tokens: ['fiscal', 'year'], domain: 'finance', pmi: 3.10 },
  { tokens: ['tax', 'deductible'], domain: 'finance', pmi: 3.30 },
  { tokens: ['write', 'off'], domain: 'finance', pmi: 2.50 },
  { tokens: ['asset', 'depreciation'], domain: 'finance', pmi: 3.80 },
  { tokens: ['liability', 'account'], domain: 'finance', pmi: 3.20 },
  { tokens: ['equity', 'stake'], domain: 'finance', pmi: 2.90 },
  { tokens: ['interest', 'expense'], domain: 'finance', pmi: 3.00 },

  // ========== IT DOMAIN ==========
  { tokens: ['ticket', 'system'], domain: 'IT', pmi: 3.50 },
  { tokens: ['help', 'desk'], domain: 'IT', pmi: 4.00 },
  { tokens: ['server', 'down'], domain: 'IT', pmi: 3.20 },
  { tokens: ['network', 'outage'], domain: 'IT', pmi: 3.80 },
  { tokens: ['vpn', 'access'], domain: 'IT', pmi: 3.40 },
  { tokens: ['password', 'reset'], domain: 'IT', pmi: 4.10 },
  { tokens: ['firewall', 'rule'], domain: 'IT', pmi: 3.60 },
  { tokens: ['backup', 'restore'], domain: 'IT', pmi: 3.30 },
  { tokens: ['disk', 'space'], domain: 'IT', pmi: 2.90 },
  { tokens: ['domain', 'controller'], domain: 'IT', pmi: 4.20 },
  { tokens: ['active', 'directory'], domain: 'IT', pmi: 4.30 },
  { tokens: ['patch', 'management'], domain: 'IT', pmi: 3.70 },
  { tokens: ['endpoint', 'security'], domain: 'IT', pmi: 3.50 },
  { tokens: ['antivirus', 'scan'], domain: 'IT', pmi: 3.40 },
  { tokens: ['ssl', 'certificate'], domain: 'IT', pmi: 3.90 },
  { tokens: ['dns', 'resolution'], domain: 'IT', pmi: 3.60 },
  { tokens: ['dhcp', 'server'], domain: 'IT', pmi: 3.80 },
  { tokens: ['load', 'balancer'], domain: 'IT', pmi: 3.30 },
  { tokens: ['virtual', 'machine'], domain: 'IT', pmi: 3.20 },
  { tokens: ['container', 'deployment'], domain: 'IT', pmi: 2.80 },
  { tokens: ['api', 'endpoint'], domain: 'IT', pmi: 2.70 },
  { tokens: ['database', 'migration'], domain: 'IT', pmi: 3.10 },
  { tokens: ['cache', 'invalidation'], domain: 'IT', pmi: 2.90 },
  { tokens: ['ssh', 'key'], domain: 'IT', pmi: 3.50 },
  { tokens: ['git', 'repository'], domain: 'IT', pmi: 3.00 },
  { tokens: ['deployment', 'pipeline'], domain: 'IT', pmi: 3.20 },
  { tokens: ['kubernetes', 'cluster'], domain: 'IT', pmi: 3.40 },
  { tokens: ['cloud', 'infrastructure'], domain: 'IT', pmi: 2.60 },
  { tokens: ['monitoring', 'dashboard'], domain: 'IT', pmi: 2.80 },
  { tokens: ['incident', 'response'], domain: 'IT', pmi: 3.00 },

  // IT ELIMINATORS (negative PMI)
  { tokens: ['door', 'ticket'], domain: 'IT', pmi: -2.10 },
  { tokens: ['concert', 'ticket'], domain: 'IT', pmi: -1.80 },
  { tokens: ['parking', 'ticket'], domain: 'IT', pmi: -1.90 },
  { tokens: ['firewall', 'brick'], domain: 'IT', pmi: -1.50 },
  { tokens: ['server', 'restaurant'], domain: 'IT', pmi: -2.00 },

  // ========== LEGAL DOMAIN ==========
  { tokens: ['contract', 'review'], domain: 'legal', pmi: 3.60 },
  { tokens: ['nda', 'agreement'], domain: 'legal', pmi: 4.00 },
  { tokens: ['terms', 'service'], domain: 'legal', pmi: 3.40 },
  { tokens: ['privacy', 'policy'], domain: 'legal', pmi: 3.50 },
  { tokens: ['intellectual', 'property'], domain: 'legal', pmi: 3.80 },
  { tokens: ['trademark', 'registration'], domain: 'legal', pmi: 3.70 },
  { tokens: ['patent', 'filing'], domain: 'legal', pmi: 3.90 },
  { tokens: ['compliance', 'audit'], domain: 'legal', pmi: 3.30 },
  { tokens: ['regulatory', 'requirement'], domain: 'legal', pmi: 3.20 },
  { tokens: ['litigation', 'risk'], domain: 'legal', pmi: 3.50 },
  { tokens: ['employment', 'agreement'], domain: 'legal', pmi: 3.40 },
  { tokens: ['non', 'compete'], domain: 'legal', pmi: 3.80 },
  { tokens: ['liability', 'waiver'], domain: 'legal', pmi: 3.60 },
  { tokens: ['indemnification', 'clause'], domain: 'legal', pmi: 4.10 },
  { tokens: ['arbitration', 'agreement'], domain: 'legal', pmi: 3.70 },
  { tokens: ['settlement', 'agreement'], domain: 'legal', pmi: 3.50 },
  { tokens: ['cease', 'desist'], domain: 'legal', pmi: 3.90 },
  { tokens: ['subpoena', 'response'], domain: 'legal', pmi: 3.80 },
  { tokens: ['discovery', 'request'], domain: 'legal', pmi: 3.40 },
  { tokens: ['deposition', 'testimony'], domain: 'legal', pmi: 3.60 },

  // ========== OPERATIONS DOMAIN ==========
  { tokens: ['vendor', 'management'], domain: 'operations', pmi: 3.20 },
  { tokens: ['supply', 'chain'], domain: 'operations', pmi: 3.50 },
  { tokens: ['inventory', 'tracking'], domain: 'operations', pmi: 3.40 },
  { tokens: ['procurement', 'process'], domain: 'operations', pmi: 3.30 },
  { tokens: ['logistics', 'coordination'], domain: 'operations', pmi: 3.10 },
  { tokens: ['quality', 'assurance'], domain: 'operations', pmi: 2.90 },
  { tokens: ['process', 'improvement'], domain: 'operations', pmi: 2.80 },
  { tokens: ['standard', 'operating'], domain: 'operations', pmi: 3.60 },
  { tokens: ['workflow', 'automation'], domain: 'operations', pmi: 3.00 },
  { tokens: ['capacity', 'planning'], domain: 'operations', pmi: 3.20 },
  { tokens: ['resource', 'allocation'], domain: 'operations', pmi: 2.90 },
  { tokens: ['bottleneck', 'analysis'], domain: 'operations', pmi: 3.10 },
  { tokens: ['throughput', 'optimization'], domain: 'operations', pmi: 3.30 },
  { tokens: ['lead', 'time'], domain: 'operations', pmi: 2.70 },
  { tokens: ['turnaround', 'time'], domain: 'operations', pmi: 2.80 },
  { tokens: ['service', 'level'], domain: 'operations', pmi: 3.00 },
  { tokens: ['performance', 'metrics'], domain: 'operations', pmi: 2.60 },
  { tokens: ['key', 'performance'], domain: 'operations', pmi: 2.70 },
  { tokens: ['operational', 'efficiency'], domain: 'operations', pmi: 3.20 },
  { tokens: ['continuous', 'improvement'], domain: 'operations', pmi: 2.90 },

  // ========== CLIENTS DOMAIN ==========
  { tokens: ['client', 'onboarding'], domain: 'clients', pmi: 3.80 },
  { tokens: ['customer', 'success'], domain: 'clients', pmi: 3.40 },
  { tokens: ['account', 'management'], domain: 'clients', pmi: 3.20 },
  { tokens: ['support', 'ticket'], domain: 'clients', pmi: 3.50 },
  { tokens: ['service', 'request'], domain: 'clients', pmi: 3.10 },
  { tokens: ['escalation', 'path'], domain: 'clients', pmi: 3.30 },
  { tokens: ['satisfaction', 'survey'], domain: 'clients', pmi: 3.00 },
  { tokens: ['retention', 'strategy'], domain: 'clients', pmi: 3.20 },
  { tokens: ['churn', 'analysis'], domain: 'clients', pmi: 3.40 },
  { tokens: ['lifetime', 'value'], domain: 'clients', pmi: 3.10 },
  { tokens: ['renewal', 'rate'], domain: 'clients', pmi: 3.30 },
  { tokens: ['upsell', 'opportunity'], domain: 'clients', pmi: 3.00 },
  { tokens: ['cross', 'sell'], domain: 'clients', pmi: 3.10 },
  { tokens: ['account', 'review'], domain: 'clients', pmi: 2.90 },
  { tokens: ['relationship', 'management'], domain: 'clients', pmi: 3.00 },
  { tokens: ['engagement', 'score'], domain: 'clients', pmi: 2.80 },
  { tokens: ['feedback', 'loop'], domain: 'clients', pmi: 2.70 },
  { tokens: ['touchpoint', 'mapping'], domain: 'clients', pmi: 2.90 },
  { tokens: ['journey', 'optimization'], domain: 'clients', pmi: 2.80 },
  { tokens: ['experience', 'improvement'], domain: 'clients', pmi: 2.60 },

  // ========== PEOPLE/HR DOMAIN ==========
  { tokens: ['employee', 'onboarding'], domain: 'people', pmi: 3.70 },
  { tokens: ['performance', 'review'], domain: 'people', pmi: 3.50 },
  { tokens: ['annual', 'review'], domain: 'people', pmi: 3.40 },
  { tokens: ['compensation', 'package'], domain: 'people', pmi: 3.60 },
  { tokens: ['benefits', 'enrollment'], domain: 'people', pmi: 3.80 },
  { tokens: ['pto', 'policy'], domain: 'people', pmi: 3.30 },
  { tokens: ['sick', 'leave'], domain: 'people', pmi: 3.20 },
  { tokens: ['parental', 'leave'], domain: 'people', pmi: 3.50 },
  { tokens: ['401k', 'matching'], domain: 'people', pmi: 3.70 },
  { tokens: ['health', 'insurance'], domain: 'people', pmi: 3.10 },
  { tokens: ['dental', 'coverage'], domain: 'people', pmi: 3.20 },
  { tokens: ['vision', 'benefits'], domain: 'people', pmi: 3.10 },
  { tokens: ['salary', 'review'], domain: 'people', pmi: 3.40 },
  { tokens: ['merit', 'increase'], domain: 'people', pmi: 3.60 },
  { tokens: ['promotion', 'criteria'], domain: 'people', pmi: 3.30 },
  { tokens: ['career', 'development'], domain: 'people', pmi: 3.00 },
  { tokens: ['succession', 'planning'], domain: 'people', pmi: 3.50 },
  { tokens: ['talent', 'acquisition'], domain: 'people', pmi: 3.20 },
  { tokens: ['recruiting', 'pipeline'], domain: 'people', pmi: 3.10 },
  { tokens: ['candidate', 'screening'], domain: 'people', pmi: 3.00 },
  { tokens: ['interview', 'process'], domain: 'people', pmi: 2.90 },
  { tokens: ['offer', 'letter'], domain: 'people', pmi: 3.40 },
  { tokens: ['background', 'check'], domain: 'people', pmi: 3.20 },
  { tokens: ['termination', 'procedure'], domain: 'people', pmi: 3.60 },
  { tokens: ['exit', 'interview'], domain: 'people', pmi: 3.50 },
  { tokens: ['employee', 'handbook'], domain: 'people', pmi: 3.70 },
  { tokens: ['code', 'conduct'], domain: 'people', pmi: 3.30 },
  { tokens: ['workplace', 'safety'], domain: 'people', pmi: 3.10 },
  { tokens: ['harassment', 'policy'], domain: 'people', pmi: 3.80 },
  { tokens: ['diversity', 'inclusion'], domain: 'people', pmi: 3.20 },

  // ========== PRO TIER ONLY: PHI (Protected Health Information) ==========
  { tokens: ['patient', 'record'], domain: 'phi_medical', pmi: 4.50, tier: 'pro' },
  { tokens: ['medical', 'history'], domain: 'phi_medical', pmi: 4.20, tier: 'pro' },
  { tokens: ['diagnosis', 'code'], domain: 'phi_medical', pmi: 4.30, tier: 'pro' },
  { tokens: ['prescription', 'medication'], domain: 'phi_medical', pmi: 4.10, tier: 'pro' },
  { tokens: ['lab', 'results'], domain: 'phi_medical', pmi: 4.00, tier: 'pro' },
  { tokens: ['treatment', 'plan'], domain: 'phi_medical', pmi: 3.90, tier: 'pro' },
  { tokens: ['health', 'record'], domain: 'phi_medical', pmi: 4.40, tier: 'pro' },
  { tokens: ['clinical', 'notes'], domain: 'phi_medical', pmi: 4.30, tier: 'pro' },
  { tokens: ['patient', 'identifier'], domain: 'phi_medical', pmi: 4.60, tier: 'pro' },
  { tokens: ['medical', 'record', 'number'], domain: 'phi_medical', pmi: 4.70, tier: 'pro' },
  { tokens: ['insurance', 'claim'], domain: 'phi_medical', pmi: 3.80, tier: 'pro' },
  { tokens: ['hipaa', 'compliance'], domain: 'phi_medical', pmi: 4.50, tier: 'pro' },

  // ========== PRO TIER ONLY: PII (Personally Identifiable Information) ==========
  { tokens: ['social', 'security', 'number'], domain: 'pii_identity', pmi: 5.00, tier: 'pro' },
  { tokens: ['ssn', 'verification'], domain: 'pii_identity', pmi: 4.80, tier: 'pro' },
  { tokens: ['drivers', 'license'], domain: 'pii_identity', pmi: 4.50, tier: 'pro' },
  { tokens: ['passport', 'number'], domain: 'pii_identity', pmi: 4.60, tier: 'pro' },
  { tokens: ['birth', 'certificate'], domain: 'pii_identity', pmi: 4.40, tier: 'pro' },
  { tokens: ['date', 'birth'], domain: 'pii_identity', pmi: 4.00, tier: 'pro' },
  { tokens: ['mothers', 'maiden'], domain: 'pii_identity', pmi: 4.70, tier: 'pro' },
  { tokens: ['credit', 'card', 'number'], domain: 'pii_financial', pmi: 4.90, tier: 'pro' },
  { tokens: ['bank', 'account', 'number'], domain: 'pii_financial', pmi: 4.80, tier: 'pro' },
  { tokens: ['routing', 'number'], domain: 'pii_financial', pmi: 4.50, tier: 'pro' },
  { tokens: ['pin', 'number'], domain: 'pii_financial', pmi: 4.40, tier: 'pro' },
  { tokens: ['cvv', 'code'], domain: 'pii_financial', pmi: 4.60, tier: 'pro' },
  { tokens: ['tax', 'identification'], domain: 'pii_financial', pmi: 4.30, tier: 'pro' },
  { tokens: ['ein', 'number'], domain: 'pii_financial', pmi: 4.20, tier: 'pro' },
  { tokens: ['biometric', 'data'], domain: 'pii_biometric', pmi: 4.70, tier: 'pro' },
  { tokens: ['fingerprint', 'scan'], domain: 'pii_biometric', pmi: 4.50, tier: 'pro' },
  { tokens: ['facial', 'recognition'], domain: 'pii_biometric', pmi: 4.40, tier: 'pro' },
  { tokens: ['dna', 'profile'], domain: 'pii_biometric', pmi: 4.80, tier: 'pro' },
  { tokens: ['home', 'address'], domain: 'pii_contact', pmi: 3.80, tier: 'pro' },
  { tokens: ['phone', 'number'], domain: 'pii_contact', pmi: 3.50, tier: 'pro' },
  { tokens: ['email', 'address'], domain: 'pii_contact', pmi: 3.40, tier: 'pro' },

  // ========== ADDITIONAL PLATFORM COMBOS (expanding to ~572) ==========
  // Finance - additional
  { tokens: ['amortization', 'schedule'], domain: 'finance', pmi: 3.50 },
  { tokens: ['capital', 'expenditure'], domain: 'finance', pmi: 3.30 },
  { tokens: ['operating', 'expense'], domain: 'finance', pmi: 3.20 },
  { tokens: ['gross', 'margin'], domain: 'finance', pmi: 3.40 },
  { tokens: ['net', 'income'], domain: 'finance', pmi: 3.30 },
  { tokens: ['ebitda', 'calculation'], domain: 'finance', pmi: 3.80 },
  { tokens: ['working', 'capital'], domain: 'finance', pmi: 3.40 },
  { tokens: ['debt', 'equity'], domain: 'finance', pmi: 3.20 },
  { tokens: ['return', 'investment'], domain: 'finance', pmi: 3.10 },
  { tokens: ['internal', 'rate'], domain: 'finance', pmi: 3.30 },
  { tokens: ['net', 'present', 'value'], domain: 'finance', pmi: 3.60 },
  { tokens: ['break', 'even'], domain: 'finance', pmi: 3.00 },
  { tokens: ['variance', 'analysis'], domain: 'finance', pmi: 3.20 },
  { tokens: ['budget', 'variance'], domain: 'finance', pmi: 3.10 },
  { tokens: ['cost', 'benefit'], domain: 'finance', pmi: 2.90 },
  { tokens: ['financial', 'statement'], domain: 'finance', pmi: 3.50 },
  { tokens: ['income', 'statement'], domain: 'finance', pmi: 3.60 },
  { tokens: ['cash', 'flow', 'statement'], domain: 'finance', pmi: 3.70 },
  { tokens: ['equity', 'statement'], domain: 'finance', pmi: 3.40 },
  { tokens: ['notes', 'payable'], domain: 'finance', pmi: 3.30 },
  { tokens: ['notes', 'receivable'], domain: 'finance', pmi: 3.30 },
  { tokens: ['accounts', 'aging'], domain: 'finance', pmi: 3.40 },
  { tokens: ['bad', 'debt'], domain: 'finance', pmi: 3.20 },
  { tokens: ['allowance', 'doubtful'], domain: 'finance', pmi: 3.60 },
  { tokens: ['prepaid', 'expense'], domain: 'finance', pmi: 3.30 },
  { tokens: ['accrued', 'expense'], domain: 'finance', pmi: 3.40 },
  { tokens: ['deferred', 'revenue'], domain: 'finance', pmi: 3.50 },
  { tokens: ['unearned', 'revenue'], domain: 'finance', pmi: 3.40 },
  { tokens: ['retained', 'earnings'], domain: 'finance', pmi: 3.60 },
  { tokens: ['dividend', 'distribution'], domain: 'finance', pmi: 3.30 },

  // IT - additional
  { tokens: ['access', 'control'], domain: 'IT', pmi: 3.20 },
  { tokens: ['authentication', 'token'], domain: 'IT', pmi: 3.40 },
  { tokens: ['two', 'factor'], domain: 'IT', pmi: 3.60 },
  { tokens: ['multifactor', 'authentication'], domain: 'IT', pmi: 3.80 },
  { tokens: ['single', 'sign', 'on'], domain: 'IT', pmi: 3.70 },
  { tokens: ['identity', 'provider'], domain: 'IT', pmi: 3.30 },
  { tokens: ['oauth', 'token'], domain: 'IT', pmi: 3.50 },
  { tokens: ['api', 'key'], domain: 'IT', pmi: 3.40 },
  { tokens: ['encryption', 'key'], domain: 'IT', pmi: 3.60 },
  { tokens: ['private', 'key'], domain: 'IT', pmi: 3.50 },
  { tokens: ['public', 'key'], domain: 'IT', pmi: 3.50 },
  { tokens: ['certificate', 'authority'], domain: 'IT', pmi: 3.70 },
  { tokens: ['intrusion', 'detection'], domain: 'IT', pmi: 3.60 },
  { tokens: ['vulnerability', 'scan'], domain: 'IT', pmi: 3.50 },
  { tokens: ['penetration', 'test'], domain: 'IT', pmi: 3.40 },
  { tokens: ['security', 'audit'], domain: 'IT', pmi: 3.30 },
  { tokens: ['threat', 'intelligence'], domain: 'IT', pmi: 3.50 },
  { tokens: ['malware', 'detection'], domain: 'IT', pmi: 3.60 },
  { tokens: ['ransomware', 'protection'], domain: 'IT', pmi: 3.70 },
  { tokens: ['data', 'breach'], domain: 'IT', pmi: 3.40 },
  { tokens: ['incident', 'report'], domain: 'IT', pmi: 3.20 },
  { tokens: ['root', 'cause'], domain: 'IT', pmi: 3.10 },
  { tokens: ['postmortem', 'analysis'], domain: 'IT', pmi: 3.30 },
  { tokens: ['change', 'management'], domain: 'IT', pmi: 3.00 },
  { tokens: ['release', 'notes'], domain: 'IT', pmi: 2.90 },
  { tokens: ['version', 'control'], domain: 'IT', pmi: 3.20 },
  { tokens: ['code', 'review'], domain: 'IT', pmi: 3.10 },
  { tokens: ['pull', 'request'], domain: 'IT', pmi: 3.30 },
  { tokens: ['merge', 'conflict'], domain: 'IT', pmi: 3.20 },
  { tokens: ['continuous', 'integration'], domain: 'IT', pmi: 3.40 },
  { tokens: ['continuous', 'deployment'], domain: 'IT', pmi: 3.40 },
  { tokens: ['build', 'pipeline'], domain: 'IT', pmi: 3.30 },
  { tokens: ['test', 'coverage'], domain: 'IT', pmi: 3.00 },
  { tokens: ['unit', 'test'], domain: 'IT', pmi: 3.10 },
  { tokens: ['integration', 'test'], domain: 'IT', pmi: 3.20 },
  { tokens: ['regression', 'test'], domain: 'IT', pmi: 3.30 },
  { tokens: ['smoke', 'test'], domain: 'IT', pmi: 3.00 },
  { tokens: ['load', 'test'], domain: 'IT', pmi: 3.20 },
  { tokens: ['stress', 'test'], domain: 'IT', pmi: 3.20 },
  { tokens: ['performance', 'test'], domain: 'IT', pmi: 3.10 },

  // Legal - additional
  { tokens: ['force', 'majeure'], domain: 'legal', pmi: 4.20 },
  { tokens: ['boilerplate', 'language'], domain: 'legal', pmi: 3.50 },
  { tokens: ['severability', 'clause'], domain: 'legal', pmi: 4.00 },
  { tokens: ['governing', 'law'], domain: 'legal', pmi: 3.80 },
  { tokens: ['jurisdiction', 'venue'], domain: 'legal', pmi: 3.90 },
  { tokens: ['statute', 'limitations'], domain: 'legal', pmi: 3.70 },
  { tokens: ['breach', 'contract'], domain: 'legal', pmi: 3.60 },
  { tokens: ['material', 'breach'], domain: 'legal', pmi: 3.80 },
  { tokens: ['cure', 'period'], domain: 'legal', pmi: 3.50 },
  { tokens: ['termination', 'cause'], domain: 'legal', pmi: 3.60 },
  { tokens: ['termination', 'convenience'], domain: 'legal', pmi: 3.70 },
  { tokens: ['notice', 'period'], domain: 'legal', pmi: 3.40 },
  { tokens: ['renewal', 'term'], domain: 'legal', pmi: 3.50 },
  { tokens: ['automatic', 'renewal'], domain: 'legal', pmi: 3.60 },
  { tokens: ['opt', 'out'], domain: 'legal', pmi: 3.30 },
  { tokens: ['right', 'refusal'], domain: 'legal', pmi: 3.70 },
  { tokens: ['assignment', 'rights'], domain: 'legal', pmi: 3.60 },
  { tokens: ['sublicense', 'rights'], domain: 'legal', pmi: 3.80 },
  { tokens: ['license', 'grant'], domain: 'legal', pmi: 3.50 },
  { tokens: ['scope', 'work'], domain: 'legal', pmi: 3.40 },
  { tokens: ['deliverable', 'acceptance'], domain: 'legal', pmi: 3.50 },
  { tokens: ['milestone', 'payment'], domain: 'legal', pmi: 3.40 },
  { tokens: ['late', 'fee'], domain: 'legal', pmi: 3.20 },
  { tokens: ['liquidated', 'damages'], domain: 'legal', pmi: 3.90 },
  { tokens: ['limitation', 'liability'], domain: 'legal', pmi: 4.00 },
  { tokens: ['disclaimer', 'warranties'], domain: 'legal', pmi: 3.80 },
  { tokens: ['implied', 'warranty'], domain: 'legal', pmi: 3.70 },
  { tokens: ['express', 'warranty'], domain: 'legal', pmi: 3.70 },
  { tokens: ['merchantability', 'fitness'], domain: 'legal', pmi: 4.10 },
  { tokens: ['confidentiality', 'obligation'], domain: 'legal', pmi: 3.90 },

  // Operations - additional
  { tokens: ['demand', 'forecasting'], domain: 'operations', pmi: 3.30 },
  { tokens: ['safety', 'stock'], domain: 'operations', pmi: 3.40 },
  { tokens: ['reorder', 'point'], domain: 'operations', pmi: 3.50 },
  { tokens: ['economic', 'order'], domain: 'operations', pmi: 3.30 },
  { tokens: ['just', 'time'], domain: 'operations', pmi: 3.40 },
  { tokens: ['kanban', 'system'], domain: 'operations', pmi: 3.50 },
  { tokens: ['lean', 'manufacturing'], domain: 'operations', pmi: 3.60 },
  { tokens: ['six', 'sigma'], domain: 'operations', pmi: 3.70 },
  { tokens: ['total', 'quality'], domain: 'operations', pmi: 3.40 },
  { tokens: ['statistical', 'process'], domain: 'operations', pmi: 3.50 },
  { tokens: ['root', 'cause', 'analysis'], domain: 'operations', pmi: 3.30 },
  { tokens: ['fishbone', 'diagram'], domain: 'operations', pmi: 3.60 },
  { tokens: ['pareto', 'analysis'], domain: 'operations', pmi: 3.50 },
  { tokens: ['value', 'stream'], domain: 'operations', pmi: 3.40 },
  { tokens: ['cycle', 'time'], domain: 'operations', pmi: 3.30 },
  { tokens: ['takt', 'time'], domain: 'operations', pmi: 3.60 },
  { tokens: ['overall', 'equipment'], domain: 'operations', pmi: 3.50 },
  { tokens: ['downtime', 'tracking'], domain: 'operations', pmi: 3.30 },
  { tokens: ['preventive', 'maintenance'], domain: 'operations', pmi: 3.40 },
  { tokens: ['predictive', 'maintenance'], domain: 'operations', pmi: 3.50 },
  { tokens: ['mean', 'time', 'failure'], domain: 'operations', pmi: 3.60 },
  { tokens: ['mean', 'time', 'repair'], domain: 'operations', pmi: 3.60 },
  { tokens: ['first', 'pass', 'yield'], domain: 'operations', pmi: 3.50 },
  { tokens: ['defect', 'rate'], domain: 'operations', pmi: 3.40 },
  { tokens: ['scrap', 'rate'], domain: 'operations', pmi: 3.50 },
  { tokens: ['rework', 'cost'], domain: 'operations', pmi: 3.40 },
  { tokens: ['cost', 'quality'], domain: 'operations', pmi: 3.30 },
  { tokens: ['appraisal', 'cost'], domain: 'operations', pmi: 3.40 },
  { tokens: ['prevention', 'cost'], domain: 'operations', pmi: 3.40 },
  { tokens: ['failure', 'cost'], domain: 'operations', pmi: 3.30 },

  // Clients - additional
  { tokens: ['net', 'promoter'], domain: 'clients', pmi: 3.50 },
  { tokens: ['customer', 'satisfaction'], domain: 'clients', pmi: 3.30 },
  { tokens: ['effort', 'score'], domain: 'clients', pmi: 3.20 },
  { tokens: ['voice', 'customer'], domain: 'clients', pmi: 3.40 },
  { tokens: ['customer', 'journey'], domain: 'clients', pmi: 3.30 },
  { tokens: ['pain', 'point'], domain: 'clients', pmi: 3.00 },
  { tokens: ['value', 'proposition'], domain: 'clients', pmi: 3.10 },
  { tokens: ['unique', 'selling'], domain: 'clients', pmi: 3.20 },
  { tokens: ['competitive', 'advantage'], domain: 'clients', pmi: 3.00 },
  { tokens: ['market', 'positioning'], domain: 'clients', pmi: 3.10 },
  { tokens: ['brand', 'awareness'], domain: 'clients', pmi: 3.00 },
  { tokens: ['customer', 'acquisition'], domain: 'clients', pmi: 3.30 },
  { tokens: ['acquisition', 'cost'], domain: 'clients', pmi: 3.40 },
  { tokens: ['conversion', 'rate'], domain: 'clients', pmi: 3.20 },
  { tokens: ['funnel', 'optimization'], domain: 'clients', pmi: 3.30 },
  { tokens: ['lead', 'generation'], domain: 'clients', pmi: 3.20 },
  { tokens: ['lead', 'qualification'], domain: 'clients', pmi: 3.30 },
  { tokens: ['sales', 'pipeline'], domain: 'clients', pmi: 3.40 },
  { tokens: ['opportunity', 'management'], domain: 'clients', pmi: 3.20 },
  { tokens: ['win', 'rate'], domain: 'clients', pmi: 3.10 },
  { tokens: ['deal', 'velocity'], domain: 'clients', pmi: 3.20 },
  { tokens: ['sales', 'cycle'], domain: 'clients', pmi: 3.30 },
  { tokens: ['average', 'deal', 'size'], domain: 'clients', pmi: 3.20 },
  { tokens: ['quota', 'attainment'], domain: 'clients', pmi: 3.40 },
  { tokens: ['forecast', 'accuracy'], domain: 'clients', pmi: 3.10 },
  { tokens: ['pipeline', 'coverage'], domain: 'clients', pmi: 3.20 },
  { tokens: ['sales', 'effectiveness'], domain: 'clients', pmi: 3.10 },
  { tokens: ['territory', 'management'], domain: 'clients', pmi: 3.30 },
  { tokens: ['account', 'planning'], domain: 'clients', pmi: 3.20 },
  { tokens: ['strategic', 'account'], domain: 'clients', pmi: 3.30 },

  // People/HR - additional
  { tokens: ['competency', 'framework'], domain: 'people', pmi: 3.50 },
  { tokens: ['job', 'description'], domain: 'people', pmi: 3.30 },
  { tokens: ['role', 'responsibilities'], domain: 'people', pmi: 3.20 },
  { tokens: ['organizational', 'chart'], domain: 'people', pmi: 3.40 },
  { tokens: ['reporting', 'structure'], domain: 'people', pmi: 3.30 },
  { tokens: ['span', 'control'], domain: 'people', pmi: 3.50 },
  { tokens: ['management', 'layer'], domain: 'people', pmi: 3.20 },
  { tokens: ['headcount', 'planning'], domain: 'people', pmi: 3.60 },
  { tokens: ['workforce', 'planning'], domain: 'people', pmi: 3.50 },
  { tokens: ['staffing', 'model'], domain: 'people', pmi: 3.40 },
  { tokens: ['skill', 'gap'], domain: 'people', pmi: 3.30 },
  { tokens: ['training', 'development'], domain: 'people', pmi: 3.20 },
  { tokens: ['learning', 'management'], domain: 'people', pmi: 3.30 },
  { tokens: ['professional', 'development'], domain: 'people', pmi: 3.20 },
  { tokens: ['knowledge', 'transfer'], domain: 'people', pmi: 3.10 },
  { tokens: ['mentorship', 'program'], domain: 'people', pmi: 3.40 },
  { tokens: ['buddy', 'system'], domain: 'people', pmi: 3.30 },
  { tokens: ['employee', 'engagement'], domain: 'people', pmi: 3.50 },
  { tokens: ['morale', 'survey'], domain: 'people', pmi: 3.40 },
  { tokens: ['pulse', 'survey'], domain: 'people', pmi: 3.50 },
  { tokens: ['stay', 'interview'], domain: 'people', pmi: 3.60 },
  { tokens: ['turnover', 'rate'], domain: 'people', pmi: 3.50 },
  { tokens: ['attrition', 'analysis'], domain: 'people', pmi: 3.60 },
  { tokens: ['retention', 'bonus'], domain: 'people', pmi: 3.70 },
  { tokens: ['sign', 'bonus'], domain: 'people', pmi: 3.60 },
  { tokens: ['equity', 'grant'], domain: 'people', pmi: 3.50 },
  { tokens: ['stock', 'option'], domain: 'people', pmi: 3.60 },
  { tokens: ['vesting', 'schedule'], domain: 'people', pmi: 3.70 },
  { tokens: ['cliff', 'period'], domain: 'people', pmi: 3.60 },
  { tokens: ['performance', 'improvement'], domain: 'people', pmi: 3.50 },
  { tokens: ['corrective', 'action'], domain: 'people', pmi: 3.60 },
  { tokens: ['disciplinary', 'action'], domain: 'people', pmi: 3.70 },
  { tokens: ['written', 'warning'], domain: 'people', pmi: 3.60 },
  { tokens: ['final', 'warning'], domain: 'people', pmi: 3.70 },
  { tokens: ['progressive', 'discipline'], domain: 'people', pmi: 3.80 },
  { tokens: ['grievance', 'procedure'], domain: 'people', pmi: 3.70 },
  { tokens: ['dispute', 'resolution'], domain: 'people', pmi: 3.50 },
  { tokens: ['conflict', 'mediation'], domain: 'people', pmi: 3.60 },
  { tokens: ['workplace', 'investigation'], domain: 'people', pmi: 3.80 },
  { tokens: ['equal', 'opportunity'], domain: 'people', pmi: 3.50 },
  { tokens: ['affirmative', 'action'], domain: 'people', pmi: 3.60 },
  { tokens: ['reasonable', 'accommodation'], domain: 'people', pmi: 3.70 },
  { tokens: ['ada', 'compliance'], domain: 'people', pmi: 3.80 },
  { tokens: ['fmla', 'leave'], domain: 'people', pmi: 3.90 },
  { tokens: ['workers', 'compensation'], domain: 'people', pmi: 3.70 },
  { tokens: ['unemployment', 'claim'], domain: 'people', pmi: 3.60 },
  { tokens: ['wage', 'garnishment'], domain: 'people', pmi: 3.70 },
  { tokens: ['time', 'attendance'], domain: 'people', pmi: 3.50 },
  { tokens: ['overtime', 'policy'], domain: 'people', pmi: 3.60 },
  { tokens: ['exempt', 'nonexempt'], domain: 'people', pmi: 3.70 },
  { tokens: ['flsa', 'compliance'], domain: 'people', pmi: 3.80 },
];

/**
 * Get seed combos for the specified tier
 * Free tier: excludes pro-only entries
 * Pro tier: returns all entries
 */
export function getSeedCombos(tier: 'free' | 'pro'): DisambiguationCombo[] {
  if (tier === 'pro') {
    return SEED_COMBOS;
  }
  // Free tier: filter out pro-only entries
  return SEED_COMBOS.filter(combo => combo.tier !== 'pro');
}

/**
 * Get count of seed combos by tier
 */
export function getSeedComboCount(tier: 'free' | 'pro'): number {
  return getSeedCombos(tier).length;
}
